# Generated by Django 5.2.7 on 2025-10-16 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_data', models.JSONField(blank=True, default=dict, verbose_name='식품 정보')),
                ('source', models.CharField(choices=[('barcode', '바코드 스캔'), ('receipt', '영수증 스캔'), ('manual', '수동 입력'), ('ai_scan', 'AI 스캔')], default='manual', max_length=10, verbose_name='입력 방식')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity', models.IntegerField(default=1)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('storage_type', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '식품',
                'verbose_name_plural': '식품 목록',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='interface_f_created_7bdfd8_idx')],
            },
        ),
    ]
