# Generated by Django 5.1.2 on 2024-11-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_data', models.JSONField(verbose_name='식품 정보')),
                ('source', models.CharField(choices=[('barcode', '바코드 스캔'), ('receipt', '영수증 스캔'), ('manual', '수동 입력')], default='manual', max_length=10, verbose_name='입력 방식')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '식품',
                'verbose_name_plural': '식품 목록',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='myapp_foodi_created_b6656f_idx')],
            },
        ),
    ]
